# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_webhook.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import livekit_models_pb2 as livekit__models__pb2
from . import livekit_recording_pb2 as livekit__recording__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="livekit_webhook.proto",
    package="livekit",
    syntax="proto3",
    serialized_options=b"Z#github.com/livekit/protocol/livekit",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x15livekit_webhook.proto\x12\x07livekit\x1a\x14livekit_models.proto\x1a\x17livekit_recording.proto"\x99\x01\n\x0cWebhookEvent\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x1b\n\x04room\x18\x02 \x01(\x0b\x32\r.livekit.Room\x12-\n\x0bparticipant\x18\x03 \x01(\x0b\x32\x18.livekit.ParticipantInfo\x12.\n\x0erecording_info\x18\x05 \x01(\x0b\x32\x16.livekit.RecordingInfoB%Z#github.com/livekit/protocol/livekitb\x06proto3',
    dependencies=[
        livekit__models__pb2.DESCRIPTOR,
        livekit__recording__pb2.DESCRIPTOR,
    ],
)


_WEBHOOKEVENT = _descriptor.Descriptor(
    name="WebhookEvent",
    full_name="livekit.WebhookEvent",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="event",
            full_name="livekit.WebhookEvent.event",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="room",
            full_name="livekit.WebhookEvent.room",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="participant",
            full_name="livekit.WebhookEvent.participant",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="recording_info",
            full_name="livekit.WebhookEvent.recording_info",
            index=3,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=235,
)

_WEBHOOKEVENT.fields_by_name["room"].message_type = livekit__models__pb2._ROOM
_WEBHOOKEVENT.fields_by_name[
    "participant"
].message_type = livekit__models__pb2._PARTICIPANTINFO
_WEBHOOKEVENT.fields_by_name[
    "recording_info"
].message_type = livekit__recording__pb2._RECORDINGINFO
DESCRIPTOR.message_types_by_name["WebhookEvent"] = _WEBHOOKEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebhookEvent = _reflection.GeneratedProtocolMessageType(
    "WebhookEvent",
    (_message.Message,),
    {
        "DESCRIPTOR": _WEBHOOKEVENT,
        "__module__": "livekit_webhook_pb2"
        # @@protoc_insertion_point(class_scope:livekit.WebhookEvent)
    },
)
_sym_db.RegisterMessage(WebhookEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
